version: '3.8'
services:
  nginx:
    # official nginx image
    image: library/nginx:1.19-alpine
    container_name: "aj_laravel_nginx"
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "../:/var/www/html"
  php:
    # my PHP image
    image: marmot00/php-fpm:7.4
    container_name: "aj_laravel_php"
    ports:
      - 9000:9000
    volumes:
      - "../:/var/www/html"